package space.tanagra.ccsds124;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

/**
 * Cross-language differential test (issue #105).
 *
 * <p>Drives the low-level {@link Compressor} over the shared corpus in {@code
 * test-vectors/differential/cases.json} and asserts byte-identical output to the C reference
 * golden, the systemic guard against "fixed-in-C-not-ported" drift (D0=M0 #98, MSB-aligned NOT
 * #103), which only shows up for non-byte-aligned F / non-zero M0.
 *
 * <p>The golden is generated by {@code test-vectors/differential/gen_golden.c}. There is no JSON
 * dependency, so the regular fixture is hand-parsed and the per-packet flags are recomputed with
 * the documented flag-timing algorithm (validated against C by the generator's self-check).
 */
final class DifferentialTest {

  private static final Path CASES_PATH = Paths.get("../../test-vectors/differential/cases.json");

  private static final class Case {
    String id;
    int f;
    int r;
    int pt;
    int ft;
    int rt;
    byte[] m0;
    List<byte[]> packets;
    String compressed;
  }

  private static String readFixture() throws IOException {
    return new String(Files.readAllBytes(CASES_PATH), java.nio.charset.StandardCharsets.UTF_8);
  }

  private static int fieldInt(String chunk, String key) {
    String needle = "\"" + key + "\":";
    int start = chunk.indexOf(needle) + needle.length();
    while (start < chunk.length() && !Character.isDigit(chunk.charAt(start))) {
      start++;
    }
    int end = start;
    while (end < chunk.length() && Character.isDigit(chunk.charAt(end))) {
      end++;
    }
    return Integer.parseInt(chunk.substring(start, end));
  }

  private static String fieldStr(String chunk, String key) {
    String needle = "\"" + key + "\": \"";
    int start = chunk.indexOf(needle) + needle.length();
    int end = chunk.indexOf('"', start);
    return chunk.substring(start, end);
  }

  private static List<byte[]> fieldStrArrayBytes(String chunk, String key) {
    String needle = "\"" + key + "\": [";
    int start = chunk.indexOf(needle) + needle.length();
    int end = chunk.indexOf(']', start);
    List<byte[]> out = new ArrayList<>();
    for (String tok : chunk.substring(start, end).split(",")) {
      String hex = tok.trim().replace("\"", "");
      if (!hex.isEmpty()) {
        out.add(hexToBytes(hex));
      }
    }
    return out;
  }

  private static byte[] hexToBytes(String s) {
    byte[] out = new byte[s.length() / 2];
    for (int i = 0; i < out.length; i++) {
      out[i] = (byte) Integer.parseInt(s.substring(2 * i, 2 * i + 2), 16);
    }
    return out;
  }

  private static String bytesToHex(byte[] b) {
    StringBuilder sb = new StringBuilder(b.length * 2);
    for (byte x : b) {
      sb.append(String.format("%02x", x & 0xFF));
    }
    return sb.toString();
  }

  private static List<Case> loadCases() throws IOException {
    String doc = readFixture();
    List<Case> cases = new ArrayList<>();
    String[] chunks = doc.split("\"id\":");
    for (int i = 1; i < chunks.length; i++) {
      String chunk = chunks[i];
      Case c = new Case();
      c.id = chunk.substring(chunk.indexOf('"') + 1, chunk.indexOf('"', chunk.indexOf('"') + 1));
      c.f = fieldInt(chunk, "F");
      c.r = fieldInt(chunk, "R");
      c.pt = fieldInt(chunk, "pt");
      c.ft = fieldInt(chunk, "ft");
      c.rt = fieldInt(chunk, "rt");
      c.m0 = hexToBytes(fieldStr(chunk, "m0"));
      c.packets = fieldStrArrayBytes(chunk, "packets");
      c.compressed = fieldStr(chunk, "compressed");
      cases.add(c);
    }
    return cases;
  }

  /**
   * Recompute the per-packet flags exactly as the C reference does (init phase forces ft=rt=1, pt=0
   * for the first R+1 packets; otherwise countdown counters fire at 1 and reload). Validated
   * against C.
   */
  private static boolean[][] flagsFor(int npk, int r, int pt, int ft, int rt) {
    boolean[][] out = new boolean[npk][3]; // [pt, ft, rt]
    int ftc = ft;
    int ptc = pt;
    int rtc = rt;
    for (int p = 0; p < npk; p++) {
      boolean ptF;
      boolean ftF;
      boolean rtF;
      if (p == 0) {
        ftF = true;
        rtF = true;
        ptF = false;
      } else {
        ftF = ftc == 1;
        ftc = ftF ? ft : ftc - 1;
        ptF = ptc == 1;
        ptc = ptF ? pt : ptc - 1;
        rtF = rtc == 1;
        rtc = rtF ? rt : rtc - 1;
      }
      if (p <= r) {
        ftF = true;
        rtF = true;
        ptF = false;
      }
      out[p][0] = ptF;
      out[p][1] = ftF;
      out[p][2] = rtF;
    }
    return out;
  }

  /** Java's compressed output must be byte-identical to the C reference for every case. */
  @TestFactory
  List<DynamicTest> compressMatchesCGolden() throws IOException {
    List<DynamicTest> tests = new ArrayList<>();
    for (Case c : loadCases()) {
      tests.add(
          DynamicTest.dynamicTest(
              c.id,
              () -> {
                BitVector mask = BitVector.fromBytes(c.m0, c.f);
                Compressor comp = new Compressor(c.f, mask, c.r, c.pt, c.ft, c.rt);
                boolean[][] flags = flagsFor(c.packets.size(), c.r, c.pt, c.ft, c.rt);

                java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
                for (int p = 0; p < c.packets.size(); p++) {
                  BitVector input = BitVector.fromBytes(c.packets.get(p), c.f);
                  BitBuffer bb =
                      comp.compressPacketWithParams(input, flags[p][0], flags[p][1], flags[p][2]);
                  out.write(bb.toBytes());
                }
                assertEquals(
                    c.compressed,
                    bytesToHex(out.toByteArray()),
                    "case " + c.id + ": Java compressed output diverges from the C reference");
              }));
    }
    return tests;
  }

  /**
   * Round-trip via the public {@link Ccsds124#decompress}, which is byte-only and takes no M0, so
   * it applies to byte-aligned, zero-M0 cases. (Encoder-bug coverage is the byte-identity test
   * above; full round-trip is exercised in C/Python.)
   */
  @TestFactory
  List<DynamicTest> roundtripByteAligned() throws IOException {
    List<DynamicTest> tests = new ArrayList<>();
    for (Case c : loadCases()) {
      if (c.f % 8 != 0) {
        continue;
      }
      boolean zeroM0 = true;
      for (byte b : c.m0) {
        if (b != 0) {
          zeroM0 = false;
          break;
        }
      }
      if (!zeroM0) {
        continue;
      }
      tests.add(
          DynamicTest.dynamicTest(
              c.id,
              () -> {
                java.io.ByteArrayOutputStream expected = new java.io.ByteArrayOutputStream();
                for (byte[] pkt : c.packets) {
                  expected.write(pkt);
                }
                byte[] decoded = Ccsds124.decompress(hexToBytes(c.compressed), c.f / 8, c.r);
                assertArrayEquals(
                    expected.toByteArray(), decoded, "case " + c.id + ": round-trip mismatch");
              }));
    }
    assertFalse(tests.isEmpty(), "expected at least one byte-aligned zero-M0 round-trip case");
    return tests;
  }
}
