"""Cross-language differential test (issue #105).

Drives the low-level Compressor over the shared corpus in
``test-vectors/differential/cases.json`` and asserts byte-identical output to
the C reference golden — the systemic guard against "fixed-in-C-not-ported"
drift (e.g. D0=M0 #98, MSB-aligned NOT #103), which only shows up for
non-byte-aligned F / non-zero M0.

The golden is generated by ``test-vectors/differential/gen_golden.c``. The
driving recipe is uniform across all languages: init Compressor(F, M0, R,
pt, ft, rt), then per packet compress_packet(input, explicit flags) and
concatenate each packet's byte-padded output.
"""

import json
import os

import pytest

from ccsds124.bitvector import BitVector
from ccsds124.compress import Compressor, CompressParams
from ccsds124.decompress import decompress

_CASES_PATH = os.path.join(
    os.path.dirname(__file__),
    "..",
    "..",
    "..",
    "test-vectors",
    "differential",
    "cases.json",
)

with open(_CASES_PATH, encoding="utf-8") as _f:
    _CASES = json.load(_f)["cases"]


def _bv(f: int, hexstr: str) -> BitVector:
    bv = BitVector(f)
    bv.from_bytes(bytes.fromhex(hexstr))
    return bv


@pytest.mark.parametrize("case", _CASES, ids=[c["id"] for c in _CASES])
def test_compress_matches_c_golden(case):
    """Python's compressed output must be byte-identical to the C reference."""
    f, r = case["F"], case["R"]
    mask = _bv(f, case["m0"])
    comp = Compressor(f, r, mask, case["pt"], case["ft"], case["rt"])

    out = bytearray()
    for pkt_hex, fl in zip(case["packets"], case["flags"]):
        params = CompressParams(
            min_robustness=r,
            new_mask_flag=bool(fl["pt"]),
            send_mask_flag=bool(fl["ft"]),
            uncompressed_flag=bool(fl["rt"]),
        )
        out += comp.compress_packet(_bv(f, pkt_hex), params)

    assert out.hex() == case["compressed"], (
        f"case {case['id']}: Python compressed output diverges from the C reference"
    )


@pytest.mark.parametrize("case", _CASES, ids=[c["id"] for c in _CASES])
def test_roundtrip_golden_decodes_to_input(case):
    """Decompressing the (C) golden must reproduce the original packets."""
    f, r = case["F"], case["R"]
    mask = _bv(f, case["m0"])

    expected = b"".join(bytes.fromhex(p) for p in case["packets"])
    out = decompress(bytes.fromhex(case["compressed"]), f, r, mask)
    assert out == expected, f"case {case['id']}: round-trip mismatch"
