// Cross-language differential test (issue #105).
//
// Drives the low-level Compressor over the shared corpus in
// test-vectors/differential/cases.json and asserts byte-identical output to
// the C reference golden — the systemic guard against "fixed-in-C-not-ported"
// drift (D0=M0 #98, MSB-aligned NOT #103), which only shows up for
// non-byte-aligned F / non-zero M0.
//
// The golden is generated by test-vectors/differential/gen_golden.c.
package ccsds124

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

type diffFlags struct {
	Pt int `json:"pt"`
	Ft int `json:"ft"`
	Rt int `json:"rt"`
}

type diffCase struct {
	ID         string      `json:"id"`
	F          int         `json:"F"`
	R          int         `json:"R"`
	Pt         int         `json:"pt"`
	Ft         int         `json:"ft"`
	Rt         int         `json:"rt"`
	M0         string      `json:"m0"`
	Packets    []string    `json:"packets"`
	Flags      []diffFlags `json:"flags"`
	Compressed string      `json:"compressed"`
}

func loadDiffCases(t *testing.T) []diffCase {
	t.Helper()
	path := filepath.Join("..", "..", "..", "test-vectors", "differential", "cases.json")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var doc struct {
		Cases []diffCase `json:"cases"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatalf("parse cases.json: %v", err)
	}
	return doc.Cases
}

func diffBitVector(t *testing.T, f int, hexStr string) *BitVector {
	t.Helper()
	b, err := hex.DecodeString(hexStr)
	if err != nil {
		t.Fatalf("hex decode: %v", err)
	}
	bv, err := NewBitVector(f)
	if err != nil {
		t.Fatalf("NewBitVector(%d): %v", f, err)
	}
	bv.FromBytes(b)
	return bv
}

// Compressed output must be byte-identical to the C reference for every case.
func TestDifferentialCompressMatchesCGolden(t *testing.T) {
	for _, c := range loadDiffCases(t) {
		c := c
		t.Run(c.ID, func(t *testing.T) {
			comp, err := NewCompressor(c.F, diffBitVector(t, c.F, c.M0), c.R, c.Pt, c.Ft, c.Rt)
			if err != nil {
				t.Fatalf("NewCompressor: %v", err)
			}
			var out []byte
			for i, pkt := range c.Packets {
				fl := c.Flags[i]
				params := &CompressParams{
					MinRobustness:    c.R,
					NewMaskFlag:      fl.Pt == 1,
					SendMaskFlag:     fl.Ft == 1,
					UncompressedFlag: fl.Rt == 1,
				}
				pb, err := comp.CompressPacket(diffBitVector(t, c.F, pkt), params)
				if err != nil {
					t.Fatalf("packet %d: %v", i, err)
				}
				out = append(out, pb...)
			}
			if got := hex.EncodeToString(out); got != c.Compressed {
				t.Errorf("case %s: Go compressed output diverges from the C reference", c.ID)
			}
		})
	}
}

// Round-trip via the public Decompress, which is byte-only and takes no M0,
// so it applies to byte-aligned, zero-M0 cases. (Encoder-bug coverage is the
// byte-identity test above; full round-trip is exercised in C/Python.)
func TestDifferentialRoundtripByteAligned(t *testing.T) {
	for _, c := range loadDiffCases(t) {
		c := c
		if c.F%8 != 0 {
			continue
		}
		zeroM0 := true
		for _, ch := range c.M0 {
			if ch != '0' {
				zeroM0 = false
				break
			}
		}
		if !zeroM0 {
			continue
		}
		t.Run(c.ID, func(t *testing.T) {
			var expected []byte
			for _, pkt := range c.Packets {
				b, _ := hex.DecodeString(pkt)
				expected = append(expected, b...)
			}
			compressed, _ := hex.DecodeString(c.Compressed)
			out, err := Decompress(compressed, c.F/8, c.R)
			if err != nil {
				t.Fatalf("Decompress: %v", err)
			}
			if hex.EncodeToString(out) != hex.EncodeToString(expected) {
				t.Errorf("case %s: round-trip mismatch", c.ID)
			}
		})
	}
}
