// Cross-language differential test (issue #105).
//
// Drives the low-level Compressor<N> over the shared corpus in
// test-vectors/differential/cases.json and asserts byte-identical output to the
// C reference golden, the systemic guard against "fixed-in-C-not-ported" drift
// (D0=M0 #98, MSB-aligned NOT #103), which only shows up for non-byte-aligned F
// / non-zero M0. Also round-trips the golden back to the input.
//
// The golden is generated by test-vectors/differential/gen_golden.c. There is no
// JSON dependency, so the regular fixture is hand-parsed and the per-packet flags
// are recomputed with the documented flag-timing algorithm (validated against C
// by the generator's self-check). N is a compile-time template parameter, so the
// runtime F is dispatched to the matching instantiation.

#include <catch2/catch_test_macros.hpp>

#include <array>
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "ccsds124/ccsds124.hpp"

namespace {

struct DiffCase {
    std::string id;
    int f = 0;
    int r = 0;
    int pt = 0;
    int ft = 0;
    int rt = 0;
    std::vector<std::uint8_t> m0;
    std::vector<std::vector<std::uint8_t>> packets;
    std::string compressed;
};

std::string cases_path() {
    const char* env = std::getenv("TEST_VECTORS_DIR");
    std::string base = env != nullptr ? env : "../../../test-vectors";
    return base + "/differential/cases.json";
}

std::string read_file(const std::string& path) {
    std::ifstream file(path);
    std::stringstream ss;
    ss << file.rdbuf();
    return ss.str();
}

std::vector<std::uint8_t> hex_to_bytes(const std::string& s) {
    std::vector<std::uint8_t> out;
    out.reserve(s.size() / 2);
    for (std::size_t i = 0; i + 1 < s.size(); i += 2) {
        out.push_back(static_cast<std::uint8_t>(std::stoi(s.substr(i, 2), nullptr, 16)));
    }
    return out;
}

std::string bytes_to_hex(const std::uint8_t* b, std::size_t n) {
    static const char* digits = "0123456789abcdef";
    std::string out;
    out.reserve(n * 2);
    for (std::size_t i = 0; i < n; ++i) {
        out.push_back(digits[b[i] >> 4]);
        out.push_back(digits[b[i] & 0x0F]);
    }
    return out;
}

int field_int(const std::string& chunk, const std::string& key) {
    std::string needle = "\"" + key + "\":";
    std::size_t pos = chunk.find(needle) + needle.size();
    while (pos < chunk.size() && (std::isdigit(static_cast<unsigned char>(chunk[pos])) == 0)) {
        ++pos;
    }
    return std::stoi(chunk.substr(pos));
}

std::string field_str(const std::string& chunk, const std::string& key) {
    std::string needle = "\"" + key + "\": \"";
    std::size_t start = chunk.find(needle) + needle.size();
    std::size_t end = chunk.find('"', start);
    return chunk.substr(start, end - start);
}

std::vector<std::vector<std::uint8_t>> field_packets(const std::string& chunk) {
    std::string needle = "\"packets\": [";
    std::size_t start = chunk.find(needle) + needle.size();
    std::size_t end = chunk.find(']', start);
    std::string body = chunk.substr(start, end - start);
    std::vector<std::vector<std::uint8_t>> out;
    std::size_t q = 0;
    while ((q = body.find('"', q)) != std::string::npos) {
        std::size_t q2 = body.find('"', q + 1);
        out.push_back(hex_to_bytes(body.substr(q + 1, q2 - q - 1)));
        q = q2 + 1;
    }
    return out;
}

std::vector<DiffCase> load_cases() {
    std::string doc = read_file(cases_path());
    std::vector<DiffCase> cases;
    std::size_t pos = 0;
    const std::string id_key = "\"id\":";
    while ((pos = doc.find(id_key, pos)) != std::string::npos) {
        std::size_t next = doc.find(id_key, pos + id_key.size());
        std::string chunk =
            doc.substr(pos, next == std::string::npos ? std::string::npos : next - pos);
        pos += id_key.size();

        DiffCase c;
        std::size_t q = chunk.find('"', id_key.size());
        std::size_t q2 = chunk.find('"', q + 1);
        c.id = chunk.substr(q + 1, q2 - q - 1);
        c.f = field_int(chunk, "F");
        c.r = field_int(chunk, "R");
        c.pt = field_int(chunk, "pt");
        c.ft = field_int(chunk, "ft");
        c.rt = field_int(chunk, "rt");
        c.m0 = hex_to_bytes(field_str(chunk, "m0"));
        c.packets = field_packets(chunk);
        c.compressed = field_str(chunk, "compressed");
        cases.push_back(std::move(c));
    }
    return cases;
}

// Recompute the per-packet flags exactly as the C reference does (init phase
// forces ft=rt=1, pt=0 for the first R+1 packets; otherwise countdown counters
// fire at 1 and reload). Validated against C.
struct Flag {
    bool pt;
    bool ft;
    bool rt;
};

std::vector<Flag> flags_for(std::size_t npk, int r, int pt, int ft, int rt) {
    std::vector<Flag> out(npk);
    int ftc = ft;
    int ptc = pt;
    int rtc = rt;
    for (std::size_t p = 0; p < npk; ++p) {
        bool pt_f;
        bool ft_f;
        bool rt_f;
        if (p == 0) {
            ft_f = true;
            rt_f = true;
            pt_f = false;
        } else {
            ft_f = ftc == 1;
            ftc = ft_f ? ft : ftc - 1;
            pt_f = ptc == 1;
            ptc = pt_f ? pt : ptc - 1;
            rt_f = rtc == 1;
            rtc = rt_f ? rt : rtc - 1;
        }
        if (p <= static_cast<std::size_t>(r)) {
            ft_f = true;
            rt_f = true;
            pt_f = false;
        }
        out[p] = {pt_f, ft_f, rt_f};
    }
    return out;
}

// Compress the corpus packets with Compressor<N>, byte-padding each packet's
// output, and assert the concatenation equals the C golden.
template <std::size_t N> std::string run_compress(const DiffCase& c) {
    constexpr std::size_t packet_bytes = (N + 7) / 8;

    ccsds124::BitVector<N> mask;
    mask.from_bytes(c.m0.data(), packet_bytes);

    ccsds124::Compressor<N> comp(static_cast<std::uint8_t>(c.r), c.pt, c.ft, c.rt);
    comp.set_initial_mask(mask);

    auto flags = flags_for(c.packets.size(), c.r, c.pt, c.ft, c.rt);
    std::vector<std::uint8_t> out;
    for (std::size_t p = 0; p < c.packets.size(); ++p) {
        ccsds124::BitVector<N> input;
        input.from_bytes(c.packets[p].data(), packet_bytes);

        ccsds124::CompressParams params;
        params.min_robustness = static_cast<std::uint8_t>(c.r);
        params.new_mask_flag = flags[p].pt;
        params.send_mask_flag = flags[p].ft;
        params.uncompressed_flag = flags[p].rt;

        ccsds124::BitBuffer<N * 6> bb;
        REQUIRE(comp.compress_packet(input, bb, &params) == ccsds124::Error::Ok);

        std::array<std::uint8_t, N * 6> tmp{};
        std::size_t n = bb.to_bytes(tmp.data(), tmp.size());
        out.insert(out.end(), tmp.begin(), tmp.begin() + n);
    }
    return bytes_to_hex(out.data(), out.size());
}

// Decompress the golden back to the original packets via the low-level
// Decompressor<N> (with the initial mask), so the round-trip covers
// non-byte-aligned F and non-zero M0 too.
template <std::size_t N> std::vector<std::uint8_t> run_roundtrip(const DiffCase& c) {
    constexpr std::size_t packet_bytes = (N + 7) / 8;
    auto compressed = hex_to_bytes(c.compressed);

    ccsds124::BitVector<N> mask;
    mask.from_bytes(c.m0.data(), packet_bytes);

    ccsds124::Decompressor<N> dec(static_cast<std::uint8_t>(c.r));
    dec.set_initial_mask(mask);

    ccsds124::BitReader reader(compressed.data(), compressed.size() * 8);
    std::vector<std::uint8_t> out;
    for (std::size_t p = 0; p < c.packets.size(); ++p) {
        ccsds124::BitVector<N> packet;
        REQUIRE(dec.decompress_packet(reader, packet) == ccsds124::Error::Ok);
        std::array<std::uint8_t, packet_bytes> tmp{};
        packet.to_bytes(tmp.data(), packet_bytes);
        out.insert(out.end(), tmp.begin(), tmp.end());
        reader.align_byte();
    }
    return out;
}

// Dispatch the runtime F to the matching compile-time instantiation.
template <typename Fn> auto dispatch_f(int f, Fn&& fn) {
    switch (f) {
    case 9:
        return fn(std::integral_constant<std::size_t, 9>{});
    case 12:
        return fn(std::integral_constant<std::size_t, 12>{});
    case 100:
        return fn(std::integral_constant<std::size_t, 100>{});
    case 720:
        return fn(std::integral_constant<std::size_t, 720>{});
    default:
        FAIL("unsupported F=" << f << " (add a Compressor<N> instantiation)");
        return decltype(fn(std::integral_constant<std::size_t, 9>{})){};
    }
}

std::vector<std::uint8_t> flatten_packets(const DiffCase& c) {
    std::vector<std::uint8_t> out;
    for (const auto& p : c.packets) {
        out.insert(out.end(), p.begin(), p.end());
    }
    return out;
}

} // namespace

TEST_CASE("Differential: compress matches C golden", "[differential]") {
    auto cases = load_cases();
    REQUIRE_FALSE(cases.empty());
    for (const auto& c : cases) {
        INFO("case " << c.id << ": C++ compressed output diverges from the C reference");
        std::string got = dispatch_f(c.f, [&](auto n) { return run_compress<n.value>(c); });
        REQUIRE(got == c.compressed);
    }
}

TEST_CASE("Differential: round-trip golden decodes to input", "[differential]") {
    auto cases = load_cases();
    REQUIRE_FALSE(cases.empty());
    for (const auto& c : cases) {
        INFO("case " << c.id << ": round-trip mismatch");
        auto back = dispatch_f(c.f, [&](auto n) { return run_roundtrip<n.value>(c); });
        REQUIRE(back == flatten_packets(c));
    }
}
