/*
 * Cross-language differential test — golden fixture generator (issue #105).
 *
 * Defines a shared corpus of compression cases (covering byte-aligned AND
 * non-byte-aligned F, and non-zero initial masks M0 — the inputs the
 * per-language suites miss), compresses each with the C reference (the
 * UAB-cross-validation-proven implementation), and writes cases.json.
 *
 * Each language's test then drives its own low-level Compressor over these
 * cases and asserts byte-identical output to the "compressed" golden here,
 * plus a round-trip. A divergence (e.g. D0=M0, MSB-NOT) shows up as a hex
 * mismatch — the systemic guard against "fixed-in-C-not-ported" drift.
 *
 * Driving recipe (uniform across all six languages):
 *   init Compressor(F, M0, R, pt, ft, rt)
 *   per packet: compress_packet(input, explicit {pt,ft,rt} from "flags")
 *               -> byte-pad the packet's output -> concatenate
 * Flags are recorded per packet so no language has to re-derive flag timing.
 *
 * Build (from repo root, after `cd implementations/c && make`):
 *   gcc -Iimplementations/c/include test-vectors/differential/gen_golden.c \
 *       -Limplementations/c/build -lccsds124 -o /tmp/gen_golden
 *   /tmp/gen_golden > test-vectors/differential/cases.json
 */
#include "ccsds124.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    const char *id;
    size_t F;       /* packet length in bits */
    uint8_t R;      /* robustness */
    int pt, ft, rt; /* period limits */
    size_t npk;     /* number of packets */
    int nonzero_m0; /* 1 => non-zero initial mask */
} case_t;

static const case_t CASES[] = {
    {"f720_m0_r2",  720, 2, 20, 50, 100, 8,  0}, /* byte-aligned sanity */
    {"f12_m0_r1",    12, 1,  3,  5,   7, 12, 0}, /* non-byte-aligned */
    {"f100_m0_r2",  100, 2,  4,  8,  16, 10, 0}, /* non-byte-aligned */
    {"f12_nz_r1",    12, 1,  3,  5,   7, 12, 1}, /* non-byte-aligned + non-zero M0 (D0, NOT) */
    {"f100_nz_r2",  100, 2,  4,  8,  16, 10, 1}, /* non-byte-aligned + non-zero M0 */
    {"f720_nz_r7",  720, 7, 10, 20,  50, 8,  1}, /* byte-aligned, high R, non-zero M0 */
    {"f9_nz_r1",      9, 1,  2,  3,   5, 9,  1}, /* 1 padding bit + non-zero M0 */
};
#define NCASES (sizeof(CASES) / sizeof(CASES[0]))

/* Deterministic packet byte (varies by case/packet/byte index). */
static uint8_t dbyte(int c, int p, int j) {
    return (uint8_t)((c * 131 + p * 17 + j * 7 + 11) & 0xFF);
}
/* Deterministic non-zero initial-mask byte. */
static uint8_t mbyte(int c, int j) { return (uint8_t)((c * 53 + j * 29 + 5) & 0xFF); }

/* Zero the padding bits (beyond F) in the last byte of an F-bit buffer. */
static void zero_padding(uint8_t *buf, size_t F) {
    size_t total = ((F + 7U) / 8U) * 8U;
    size_t pad = total - F;
    if (pad > 0U) {
        uint8_t keep = (uint8_t)(0xFFU << pad); /* MSB-aligned: top (8-pad) bits kept */
        buf[(F + 7U) / 8U - 1U] &= keep;
    }
}

static void print_hex(const uint8_t *b, size_t n) {
    for (size_t i = 0; i < n; i++) printf("%02x", b[i]);
}

int main(void) {
    printf("{\n  \"_comment\": \"Generated by gen_golden.c (issue #105). Golden = C reference output. Do not hand-edit.\",\n");
    printf("  \"cases\": [\n");

    for (size_t ci = 0; ci < NCASES; ci++) {
        const case_t *cs = &CASES[ci];
        size_t F = cs->F;
        size_t pkb = (F + 7U) / 8U;

        /* Build packet input bytes (byte-aligned per packet, padding zeroed). */
        uint8_t *input = (uint8_t *)calloc(cs->npk * pkb, 1);
        for (size_t p = 0; p < cs->npk; p++) {
            for (size_t j = 0; j < pkb; j++) input[p * pkb + j] = dbyte((int)ci, (int)p, (int)j);
            zero_padding(&input[p * pkb], F);
        }

        /* Initial mask M0. */
        uint8_t m0[CCSDS124_MAX_PACKET_BYTES];
        memset(m0, 0, pkb);
        if (cs->nonzero_m0) {
            for (size_t j = 0; j < pkb; j++) m0[j] = mbyte((int)ci, (int)j);
            zero_padding(m0, F);
        }
        bitvector_t mask;
        bitvector_init(&mask, F);
        bitvector_from_bytes(&mask, m0, pkb);

        /* --- Golden: bulk compress (auto flags, byte-aligned per packet) --- */
        ccsds124_compressor_t comp;
        ccsds124_compressor_init(&comp, F, &mask, cs->R, cs->pt, cs->ft, cs->rt);
        uint8_t golden[CCSDS124_MAX_OUTPUT_BYTES];
        size_t golden_len = 0;
        int rc = ccsds124_compress(&comp, input, cs->npk * pkb, golden, sizeof(golden), &golden_len);
        if (rc != CCSDS124_OK) { fprintf(stderr, "case %s: bulk compress failed (%d)\n", cs->id, rc); return 1; }

        /* --- Recompute per-packet flags (mirrors the bulk countdown) and
         *     reconstruct via per-packet compress_packet; assert == golden. --- */
        int ftc = cs->ft, ptc = cs->pt, rtc = cs->rt;
        int flag_pt[64], flag_ft[64], flag_rt[64];
        ccsds124_compressor_t comp2;
        ccsds124_compressor_init(&comp2, F, &mask, cs->R, cs->pt, cs->ft, cs->rt);
        uint8_t recon[CCSDS124_MAX_OUTPUT_BYTES];
        size_t recon_len = 0;
        for (size_t p = 0; p < cs->npk; p++) {
            int pt_f, ft_f, rt_f;
            if (p == 0) { ft_f = 1; rt_f = 1; pt_f = 0; }
            else {
                if (ftc == 1) { ft_f = 1; ftc = cs->ft; } else { ftc--; ft_f = 0; }
                if (ptc == 1) { pt_f = 1; ptc = cs->pt; } else { ptc--; pt_f = 0; }
                if (rtc == 1) { rt_f = 1; rtc = cs->rt; } else { rtc--; rt_f = 0; }
            }
            if (p <= cs->R) { ft_f = 1; rt_f = 1; pt_f = 0; } /* init-phase override */
            flag_pt[p] = pt_f; flag_ft[p] = ft_f; flag_rt[p] = rt_f;

            bitvector_t in;
            bitvector_init(&in, F);
            bitvector_from_bytes(&in, &input[p * pkb], pkb);
            bitbuffer_t bb;
            bitbuffer_init(&bb);
            ccsds124_params_t prm;
            prm.min_robustness = cs->R;
            prm.new_mask_flag = (uint8_t)pt_f;
            prm.send_mask_flag = (uint8_t)ft_f;
            prm.uncompressed_flag = (uint8_t)rt_f;
            rc = ccsds124_compress_packet(&comp2, &in, &bb, &prm);
            if (rc != CCSDS124_OK) { fprintf(stderr, "case %s pkt %zu: compress_packet failed\n", cs->id, p); return 1; }
            uint8_t pb[CCSDS124_MAX_OUTPUT_BYTES];
            size_t pn = bitbuffer_to_bytes(&bb, pb, sizeof(pb));
            memcpy(&recon[recon_len], pb, pn);
            recon_len += pn;
        }
        if (recon_len != golden_len || memcmp(recon, golden, golden_len) != 0) {
            fprintf(stderr, "case %s: per-packet reconstruct != bulk golden (recon %zu, golden %zu)\n",
                    cs->id, recon_len, golden_len);
            return 2;
        }

        /* --- Round-trip: decompress golden, assert == input --- */
        ccsds124_decompressor_t dec;
        ccsds124_decompressor_init(&dec, F, &mask, cs->R);
        uint8_t back[CCSDS124_MAX_OUTPUT_BYTES];
        size_t back_len = 0;
        rc = ccsds124_decompress(&dec, golden, golden_len, back, sizeof(back), &back_len);
        if (rc != CCSDS124_OK || back_len != cs->npk * pkb || memcmp(back, input, back_len) != 0) {
            fprintf(stderr, "case %s: round-trip failed (rc=%d, %zu vs %zu)\n", cs->id, rc, back_len, cs->npk * pkb);
            return 3;
        }

        /* --- Emit JSON --- */
        printf("    {\n");
        printf("      \"id\": \"%s\",\n", cs->id);
        printf("      \"F\": %zu, \"R\": %d, \"pt\": %d, \"ft\": %d, \"rt\": %d,\n",
               F, cs->R, cs->pt, cs->ft, cs->rt);
        printf("      \"m0\": \""); print_hex(m0, pkb); printf("\",\n");
        printf("      \"packets\": [");
        for (size_t p = 0; p < cs->npk; p++) {
            printf("%s\"", p ? ", " : ""); print_hex(&input[p * pkb], pkb); printf("\"");
        }
        printf("],\n");
        printf("      \"flags\": [");
        for (size_t p = 0; p < cs->npk; p++) {
            printf("%s{\"pt\": %d, \"ft\": %d, \"rt\": %d}", p ? ", " : "", flag_pt[p], flag_ft[p], flag_rt[p]);
        }
        printf("],\n");
        printf("      \"compressed\": \""); print_hex(golden, golden_len); printf("\"\n");
        printf("    }%s\n", (ci + 1 < NCASES) ? "," : "");

        free(input);
    }
    printf("  ]\n}\n");
    return 0;
}
